SET NAMES WIN1252;

CONNECT 'C:\AngloII\Anglo_2015II.gdb' USER 'SYSDBA' PASSWORD 'masterkey';

CREATE TABLE NEGOCIACAO (
    COD_NEGOCIACAO  INTEGER NOT NULL,
    DATA            DATE,
    QUANT           INTEGER,
    DIAS            INTEGER,
    ALUNO           INTEGER,
    VALOR           NUMERIC(9,2)
);
ALTER TABLE NEGOCIACAO ADD CONSTRAINT PK_NEGOCIACAO PRIMARY KEY (COD_NEGOCIACAO);
ALTER TABLE NEGOCIACAO ADD CONSTRAINT FK_NEGOCIACAO FOREIGN KEY (ALUNO) REFERENCES ALUNOS (CODIGO) ON UPDATE CASCADE;

CREATE TABLE BLOQUETOS_DELETE (
    NOSSO_NUMERO     INTEGER NOT NULL,
    ALUNO            INTEGER,
    PARCELA          SMALLINT,
    EMISSAO          DATE,
    VENCIMENTO       DATE,
    VALOR            VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    PAGAMENTO        DATE,
    VALOR_PAGO       VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    MENSALIDADE      VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    MATERIAL         VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    DESCONTO         VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    TIPO_PG          SMALLINT,
    ANO_DV           CHAR(2),
    DESCONTO_ANT     VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    MENSALIDADE_ANT  VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    VALOR_ANT        VALOR_MONETARIO /* VALOR_MONETARIO = NUMERIC(9,2) */,
    BAULA_AD         CHAR(1),
    ST               CHAR(1) COLLATE PXW_INTL850,
    TP               INTEGER,
    MOTIVO           VARCHAR(150) COLLATE PXW_INTL850,
    DATA_LIMITE      DATE
);

ALTER TABLE BLOQUETOS
ADD   NEGOCIACAO       INTEGER

ALTER TABLE BLOQUETOS ADD CONSTRAINT FK_BLOQUETOS FOREIGN KEY (NEGOCIACAO) REFERENCES NEGOCIACAO (COD_NEGOCIACAO) ON UPDATE CASCADE;

