SET NAMES WIN1252;

CONNECT 'C:\Anglo\AnglO.gdb' USER 'SYSDBA' PASSWORD 'masterkey';



CREATE TABLE NOTAS_PRIMEIRO (
    ALUNO       INTEGER NOT NULL,
    DISCIPLINA  INTEGER NOT NULL,
    BIMESTRE    SMALLINT NOT NULL,
    NOTA1       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA2       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA3       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA4       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA5       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA6       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA        NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM    NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM1   NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM2   NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM3   NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    STATUS      CHAR(1) DEFAULT 'S',
    USUARIO     INTEGER,
    PROFESSOR1  INTEGER,
    PROFESSOR2  INTEGER,
    PROFESSOR3  INTEGER
);

CREATE TABLE NOTAS_SEGUNDO (
    ALUNO       INTEGER NOT NULL,
    DISCIPLINA  INTEGER NOT NULL,
    BIMESTRE    SMALLINT NOT NULL,
    NOTA1       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA2       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA3       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA4       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA5       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA6       NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    NOTA        NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM    NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM1   NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM2   NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    RECUPBIM3   NOTA /* NOTA = NUMERIC(2,1) DEFAULT null */,
    STATUS      CHAR(1) DEFAULT 'S',
    USUARIO     INTEGER,
    PROFESSOR1  INTEGER,
    PROFESSOR2  INTEGER,
    PROFESSOR3  INTEGER
);

