SET NAMES WIN1252;

CONNECT '172.16.0.78:/bds/Anglo/Anglo_2015II.gdb' USER 'SYSDBA' PASSWORD 'plkh%321';


ALTER TABLE PARAMETROS DROP CONT_REMESSA;
ALTER TABLE PARAMETROS DROP DATA_REMESSA;
ALTER TABLE PARAMETROS DROP CONT_ARQ;

