INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 1, 1);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 1, 2);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 1, 12);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 1, 10);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 2, 5);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 3, 8);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 3, 6);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 3, 7);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 4, 4);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 4, 3);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 4, 19);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (1, 0, 4, 20);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 1, 13);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 1, 50);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 2, 26);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 5, 27);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 5, 28);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 5, 29);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 4, 30);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 4, 31);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 4, 32);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 2, 7, 39);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 2, 7, 34);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 2, 7, 35);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 2, 8, 36);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 2, 8, 37);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 2, 9, 14);
INSERT INTO FOR_INT (FORMACAO_CODIGO, INTINERARIOS_CODIGO, ARE_CONHECIMENTO_ID_AREA, COD_DICIPLINA)
             VALUES (2, 1, 7, 38);


COMMIT WORK;

